### PR TITLE
Feature/add formats to ajv

### PR DESCRIPTION
**Pull request by Isengo1989**

### CODE REVIEW

**Comment by Isengo1989** [comment]
@mheap PR related to -> https://github.com/mheap/frontmatter-json-schema-action/issues/6

Tested on my fork and works


```
 "authors": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "email"
      }
    },
```

Fails
```
---
.....
id: "b06c309b-0ef1-474b-9f22-a4383028e338"
authors: ["m.hobert@fail"]
...
---
```


Passes
```
---
.....
id: "b06c309b-0ef1-474b-9f22-a4383028e338"
authors: ["m.hobert@MY_MAIL.com"]
...
---
```

**Comment by mheap** [comment]
@Isengo1989 Could you add two tests please? One success and one failure

See https://github.com/mheap/frontmatter-json-schema-action/blob/main/index.test.js#L144-L183 for an example

**Comment by Isengo1989** [comment]
@mheap the tests are currently failing with 2 errors :thinking: 


```
  ✓ throws when no schema is provided (6 ms)
  ✕ throws when the provided schema is not JSON (8 ms)
  ✕ throws when the provided schema_path is not JSON (2 ms)
  ✓ throws when INPUT_PATHS is not provided (18 ms)
  ✓ throws when there are no matching files (1 ms)
  ✓ add annotations and fails when a document does not validate (6 ms)
  ✓ does not add annotations or fail when all documents are valid (2 ms)
```

I can add those, but it will fail. Is there an action for execution anyways?

Ok, missed the ci.yml :disappointed: 

I updated the action versions as well as node version matrix :wave:

**Comment by Isengo1989** [comment]
Thx for merging @mheap - noticed that the response in node 18 and 20 differ. So you might want to change it up to two steps or only check on node 20 :thinking: 

https://github.com/mheap/frontmatter-json-schema-action/actions/runs/12234657139

image

**Pull request merged**
